### ISSUE TITLE
Cross Dimensional Teleporting Temporarily Removes EXP Levels

### ISSUE THREAD

**Issue by milkev** [CodedSakura/FabricHomes#10]
When you teleport across dimensions using /home, your client visually loses all their exp levels. This can be fixed by manually going to the nether and back.  This happens on both dedicated servers and single player worlds.
I only tested with the nether, as I don't have access to the end yet in my playthrough, but I imagine a similar thing happens.

**Comment by CodedSakura** [comment]
this sounds pretty much like https://github.com/CodedSakura/FabricWarps/issues/2 and can be solved by grabbing https://modrinth.com/mod/FabricCrossDimTPFix

**Comment by milkev** [comment]
awesome, thanks!
