### ISSUE TITLE
Add support for fabric-permission-api

### ISSUE THREAD

**Issue by Veseon** [CodedSakura/FabricHomes#16]
Are there any plans on adding support for fabric-permission-api?
Would be very useful.

**Comment by CodedSakura** [comment]
to this & CodedSakura/FabricWarps#4 i can only say: probably eventually? i have a lot of stuff going on currently with uni exam season soon & other stuff, i don't really have a lot of time to maintain my mods, sorry :/

**Comment by CodedSakura** [comment]
closed by #17
