### ISSUE TITLE
Disconnect with /home <name>

### ISSUE THREAD

**Issue by DTRW919** [CodedSakura/FabricHomes#6]
Whenever I use `/home Farm` (my home name is Farm), it sends this line in the server logs and just disconnects my client. Same thing with `/gamemode <gamemode>`: 
```lost connection: Internal Exception: java.lang.NullPointerException: Cannot invoke "java.util.List.removeIf(java.util.function.Predicate)" because "this.muted" is null```

**Comment by DTRW919** [comment]
(just says disconnected on my client log)

**Comment by CodedSakura** [comment]
does the `/gamemode <gamemode>` disconnect keep happening if FabricHomes is removed?

**Comment by DTRW919** [comment]
Oh, huh it does disconnect me. Must be smth wrong with another mod/config, thanks lol.
